import type { Difficulty, Question } from '../../../../types/content';
import { sourceRefs as ref } from '../sources';

type Seed = [string,string,string[],number,string,string[],Difficulty?];
const seeds: Seed[] = [
['001','Who is directly responsible for and the final authority over a Part 107 operation?',['The visual observer','The remote pilot in command','The aircraft owner','The person who hired the crew'],1,'The remote PIC has direct responsibility and final authority for the operation.',[ref.rules]],
['002','What is the minimum age to qualify for a remote pilot certificate with a small UAS rating?',['14','16','18','21'],1,'An applicant must be at least 16 years old.',[ref.rules]],
['003','To exercise Part 107 privileges, aeronautical knowledge recency must have been completed within the preceding…',['12 calendar months','18 calendar months','24 calendar months','36 calendar months'],2,'Part 107 requires an applicable test, training, or recurrent training within the previous 24 calendar months.',[ref.rules]],
['004','An operation causes serious injury to a person. When must it be reported to the FAA?',['Within 24 hours','Within 5 days','Within 10 days','Only on request'],2,'A qualifying operation must be reported to the FAA within 10 days.',[ref.rules]],
['005','Which preflight action is required of the remote PIC?',['File a flight plan for every operation','Assess the operating environment and risks','Contact the nearest control tower in all airspace','Ask local police to approve the flight'],1,'The remote PIC must assess the environment, including local weather, airspace, people, property, and ground hazards.',[ref.rules]],
['006','A person without a remote pilot certificate may manipulate the controls when…',['the aircraft weighs less than 0.55 lb','a certificated remote PIC directly supervises and can immediately take control','a visual observer is present','the operation is in Class G airspace'],1,'A non-certificated person may manipulate the controls under direct supervision of a certificated remote PIC who can immediately take direct control.',[ref.rules]],
['007','When may a remote PIC deviate from a Part 107 rule during flight?',['Whenever the client requests it','Only after calling ATC','In an in-flight emergency requiring immediate action, to the extent necessary','Never'],2,'Section 107.21 permits a deviation only to the extent necessary to respond to an in-flight emergency.',[ref.rules]],
['008','How many small UAS operations may one person serve simultaneously as remote PIC or visual observer for?',['One','Two','Three','Any number within sight'],0,'A person may not act as remote PIC or visual observer for more than one small UAS operation at the same time.',[ref.rules]],
['009','When must a remote pilot provide their certificate and identification for inspection?',['Only after an accident','Only with a court order','Upon request by specified authorized representatives','Only at a knowledge testing center'],2,'Required documents must be presented on request to the FAA and other officials specified by § 107.7.',[ref.rules]],
['010','Which statement about alcohol is correct for a Part 107 crewmember?',['Beer is allowed below 200 ft','The 8-hour bottle-to-throttle restriction applies','Only the remote PIC is restricted','Alcohol is permitted if a visual observer agrees'],1,'Part 107 incorporates the alcohol and drug restrictions of § 91.17, including eight hours after drinking.',[ref.rules]],
['011','A small UAS must be in a condition for safe operation…',['only at annual inspection','before each flight','only when flown over people','only for commercial flights'],1,'The remote PIC must determine before each flight that the small UAS is in a condition for safe operation.',[ref.rules]],
['012','Transporting another person’s property for compensation under Part 107 is allowed only when, among other conditions…',['the flight remains wholly within one state','the aircraft is flown from a moving car','the payload weighs more than 55 lb','the route crosses an international border'],0,'Section 107.205 and § 107.25 conditions include remaining within one state and prohibit operation from a moving vehicle for this carriage.',[ref.rules],'advanced'],

['013','Before operating in Class C airspace, the remote pilot must obtain…',['airport-manager permission','prior FAA airspace authorization','a waiver of all Part 107 rules','no approval below 400 ft'],1,'Operations in Class C require prior FAA authorization.',[ref.airspace]],
['014','Which airspace normally requires no Part 107 airspace authorization?',['Class B','Class C','Class D','Class G'],3,'Class G is uncontrolled airspace and normally does not require authorization, though all other rules still apply.',[ref.airspace]],
['015','On a sectional chart, a dashed magenta line usually identifies…',['Class B airspace','surface Class E airspace','a military operations area','a prohibited area'],1,'A dashed magenta boundary depicts Class E airspace beginning at the surface.',[ref.airspace]],
['016','A fuzzy or shaded magenta boundary indicates that Class E generally begins at…',['the surface','700 feet AGL','1,200 feet AGL','18,000 feet MSL'],1,'On the faded side of a shaded magenta vignette, Class E generally begins at 700 feet AGL.',[ref.airspace]],
['017','What does a UAS Facility Map grid value represent?',['A guaranteed flight altitude','The maximum altitude likely eligible for streamlined authorization review','The top of Class G airspace','A waiver from visibility rules'],1,'Facility Map values guide authorization processing; they are not permission to fly.',[ref.airspace]],
['018','A Temporary Flight Restriction is best checked through…',['current FAA NOTAM information','the aircraft serial number','the registration card only','yesterday’s weather report'],0,'TFRs are published through the NOTAM system and must be checked as part of preflight planning.',[ref.airspace]],
['019','A remote PIC near an airport must…',['avoid interfering with airport operations and traffic patterns','always call the control tower','land on the airport runway','remain exactly 5 miles away'],0,'Part 107 prohibits operations that interfere with traffic patterns or airport operations; there is no universal five-mile rule for Part 107.',[ref.rules]],
['020','Runway 27 is aligned approximately with which magnetic direction?',['027°','090°','180°','270°'],3,'Runway numbers represent magnetic direction rounded to the nearest 10 degrees with the final zero omitted.',[ref.phak]],
['021','A prohibited area is established for…',['high-volume flight training','security or national-welfare reasons','weather observation','routine parachute jumping'],1,'Prohibited areas restrict flight for security or other national-welfare reasons.',[ref.phak]],
['022','When operating near a Military Operations Area, the best action is to…',['assume military activity stays above 400 ft','check current status and exercise extreme caution','enter freely because MOAs prohibit only crewed aircraft','contact local police for clearance'],1,'MOAs can contain high-speed military activity; check status and remain alert even though VFR entry is not automatically prohibited.',[ref.phak]],

['023','What is the maximum Part 107 groundspeed without a waiver?',['87 knots (100 mph)','100 knots (115 mph)','120 knots','150 mph'],0,'The maximum groundspeed is 87 knots, or 100 miles per hour.',[ref.limits]],
['024','What is the normal maximum altitude under Part 107?',['200 ft AGL','400 ft AGL','500 ft AGL','1,000 ft MSL'],1,'The normal ceiling is 400 feet above ground level.',[ref.limits]],
['025','A 600-foot-tall structure may be inspected at 900 feet AGL when the aircraft is…',['within 400 feet of the structure','in any Class G location','directly above a road','using a visual observer'],0,'Within 400 feet of a structure, the aircraft may fly up to 400 feet above the structure’s immediate uppermost limit, subject to other rules.',[ref.limits]],
['026','Minimum flight visibility under Part 107 is…',['1 statute mile','2 statute miles','3 statute miles','5 statute miles'],2,'Flight visibility must be at least 3 statute miles as observed from the control station.',[ref.limits]],
['027','Required cloud clearance is…',['clear of clouds only','500 ft below and 2,000 ft horizontally','1,000 ft above and 1 mile horizontally','500 ft above and 500 ft horizontally'],1,'The small UAS must remain at least 500 feet below clouds and 2,000 feet horizontally from them.',[ref.limits]],
['028','First-person-view goggles may be used when…',['they replace the need for VLOS','the VLOS requirement is still satisfied by an applicable crewmember','the aircraft is above 400 ft','ATC monitors the telemetry'],1,'FPV may assist but cannot replace the required unaided visual line of sight.',[ref.rules]],
['029','A small UAS must yield right of way to…',['only airplanes','only aircraft below 400 ft','all aircraft, airborne vehicles, and launch/reentry vehicles','only emergency helicopters'],2,'Small UAS must yield to all other aircraft and specified airborne or launch/reentry vehicles.',[ref.rules]],
['030','Operating from a moving land vehicle is permitted without a waiver only when…',['over a sparsely populated area and other conditions are met','the vehicle stays below 25 mph','the pilot uses FPV','the flight is in Class D'],0,'Part 107 permits this only over a sparsely populated area and restricts carriage of another’s property for compensation.',[ref.rules]],

['031','For routine Part 107 night operations, anti-collision lighting must be visible for at least…',['1 statute mile','2 statute miles','3 statute miles','5 statute miles'],2,'Night operations require anti-collision lighting visible for at least 3 statute miles.',[ref.night]],
['032','May the remote PIC reduce anti-collision light intensity at night?',['No, never','Yes, when the remote PIC determines operating conditions make it safer','Only below 100 ft','Only with ATC permission'],1,'The remote PIC may reduce the light intensity when it would be safer under the operating conditions.',[ref.night]],
['033','A Category 1 aircraft used over people must weigh…',['0.55 lb or less throughout the operation','less than 5 lb at takeoff','exactly 0.55 lb without payload','less than 55 lb'],0,'Category 1 is limited to 0.55 pound or less, including everything attached, throughout the operation.',[ref.people]],
['034','Which feature disqualifies an otherwise lightweight aircraft from Category 1?',['A camera','Exposed rotating parts capable of causing lacerations','A Remote ID module','Anti-collision lighting'],1,'Category 1 aircraft may not contain exposed rotating parts that would cause lacerations.',[ref.people]],
['035','Which is a valid Remote ID compliance path?',['Standard Remote ID drone','A visible registration sticker alone','Monitoring CTAF','Flying below 100 ft anywhere'],0,'Standard Remote ID is one of the compliance paths, along with a broadcast module or qualifying operation in a FRIA.',[ref.rid]],
['036','A drone using only a Remote ID broadcast module must generally be operated…',['beyond visual line of sight','within visual line of sight','only at night','only in Class B airspace'],1,'The broadcast-module path requires the person operating the drone to maintain visual line of sight.',[ref.rid]],
['037','Under Part 107, aircraft registrations are generally assigned…',['once to the pilot for every aircraft','to each individual device','only to aircraft above 55 lb','only when used over people'],1,'Part 107 pilots register each device individually in their inventory.',[ref.rid]],
['038','Routine night operation in controlled airspace also requires…',['a separate airspace authorization when applicable','a waiver in every case','a second remote PIC','a crewed-aircraft transponder'],0,'Night privileges do not replace the authorization required for controlled airspace.',[ref.night,ref.airspace]],

['039','A METAR primarily reports…',['observed weather','a 30-day climate outlook','airport construction','aircraft performance'],0,'A METAR is an aviation routine weather observation.',[ref.weather]],
['040','A TAF primarily provides…',['an airport forecast','a live radar image','a pilot medical report','a list of TFRs'],0,'A Terminal Aerodrome Forecast predicts conditions for an airport area over a stated period.',[ref.weather]],
['041','Wind reported as 18012G20KT means…',['from 180° at 12 knots, gusting 20','toward 180° at 20 mph','variable at 12 mph','from 018° at 120 knots'],0,'The group gives wind from 180 degrees true at 12 knots with gusts to 20 knots.',[ref.weather]],
['042','A small temperature/dew-point spread suggests…',['low relative humidity','air nearing saturation and possible fog or clouds','strong magnetic variation','low density altitude'],1,'As temperature and dew point converge, saturation and visibility restrictions become more likely.',[ref.weather]],
['043','Which combination produces the highest density altitude?',['Low elevation, cold temperature, high pressure','High elevation, hot temperature, low pressure','Sea level, cold temperature, high pressure','High pressure and low humidity only'],1,'High, hot, and low-pressure conditions reduce air density and increase density altitude.',[ref.phak]],
['044','High density altitude generally causes a small UAS to…',['gain propeller efficiency','require more power for the same performance','use less battery energy','become heavier on the scale'],1,'Thinner air reduces aerodynamic and propeller performance, increasing power demand.',[ref.phak]],
['045','Stable air is commonly associated with…',['smooth air, stratiform clouds, and poor visibility','severe turbulence and towering cumulus only','excellent visibility in blowing dust','rapid vertical mixing'],0,'Stable conditions resist vertical motion and favor smooth air, layered clouds, and restricted visibility.',[ref.weather]],
['046','Why are thunderstorms hazardous even when the aircraft remains outside the rain shaft?',['Outflow and turbulence can extend beyond the cell','GPS is always illegal near rain','Cloud clearance no longer applies','Battery voltage automatically doubles'],0,'Thunderstorm gust fronts, outflow, turbulence, hail, and lightning can extend well beyond visible precipitation.',[ref.weather]],

['047','Adding payload above the manufacturer’s limit will most directly…',['improve climb rate','reduce performance and safety margin','increase battery capacity','eliminate wind effects'],1,'Excess weight raises power required and can degrade climb, endurance, stability, and control.',[ref.ac]],
['048','A center of gravity outside approved limits can cause…',['reduced controllability or instability','stronger Remote ID signal','lower density altitude','automatic airspace authorization'],0,'Improper balance can exceed available control authority or destabilize the aircraft.',[ref.ac]],
['049','When planning a flight in strong wind, the safest energy strategy is to…',['fly downwind first until half the battery is used','plan the demanding upwind leg and preserve a conservative landing reserve','ignore wind if GPS is available','use the manufacturer’s maximum endurance as guaranteed time'],1,'Wind and maneuvering reduce real endurance; plan the worst leg and retain reserve for contingencies.',[ref.ac]],
['050','During a lost-link event, the crew’s best preparation is…',['deciding the response after the link fails','pre-briefing the programmed lost-link behavior and recovery area','turning off Remote ID','climbing immediately above all obstacles'],1,'The crew should know the aircraft’s programmed response, hazards, recovery area, and termination criteria before launch.',[ref.ac]],
['051','PAVE is a risk checklist for…',['Pilot, Aircraft, enVironment, and External pressures','Power, Altitude, Visibility, and Endurance','Payload, Authorization, Visual observer, and Emergency','Pilot, Airport, Vehicle, and Equipment'],0,'PAVE organizes risk around the pilot, aircraft, environment, and external pressures.',[ref.phak]],
['052','Which behavior best demonstrates effective crew resource management?',['The remote PIC discourages questions','Any crewmember clearly calls out a hazard','Only the visual observer may report traffic','Control transfers are implied, not spoken'],1,'Effective CRM uses clear roles, shared situational awareness, and assertive hazard communication.',[ref.ac]],
['053','A visual observer’s primary contribution is to…',['replace the remote PIC','help see the aircraft, scan for hazards, and communicate effectively','authorize controlled-airspace entry','repair the aircraft in flight'],1,'A VO supports VLOS and hazard detection through effective, continuous communication.',[ref.rules]],
['054','If a crewed helicopter approaches the operating area, the remote PIC should…',['hold position because the drone is lower','yield immediately and avoid creating a collision hazard','climb for better visibility','wait for the helicopter pilot to call'],1,'Small UAS must yield; the response should be early, predictable, and safe.',[ref.rules]],
['055','“Get-there-itis” is an example of…',['external pressure that can bias a go/no-go decision','a weather-report code','an airspace authorization','a battery maintenance procedure'],0,'Pressure to finish can drive plan continuation despite mounting risk and should be identified before launch.',[ref.phak]],
['056','If an uninvolved person enters the planned flight path, the remote PIC should…',['continue because the briefing already occurred','adjust or pause the operation to maintain compliance and safety','ask the person to watch the drone','increase speed to pass quickly'],1,'The remote PIC must continuously manage risk and may need to reposition, land, or pause.',[ref.rules]],
['057','A lithium battery begins smoking after landing. The first priority is to…',['place it in a pocket','protect people, isolate the hazard, and follow the emergency plan','recharge it immediately','submerge every battery type in water'],1,'Protect people and property, isolate the hazard when safe, and follow battery/manufacturer and emergency guidance.',[ref.ac]],
['058','Which preflight item best protects against a payload separation?',['Verify attachment security and weight/balance','Increase screen brightness','Switch to sport mode','Disable geofencing'],0,'Payload security and its effects on mass and balance must be checked before flight.',[ref.rules]],
['059','The purpose of a sterile-communication period is to…',['prevent all crew coordination','limit nonessential talk during critical phases','avoid monitoring aircraft traffic','replace the preflight briefing'],1,'Limiting nonessential talk helps the crew maintain focus during launch, landing, or other critical moments.',[ref.ac]],
['060','When GPS performance degrades unexpectedly, the remote PIC should first…',['continue the mission unchanged','maintain control, assess aircraft behavior, and execute the briefed contingency','climb beyond VLOS','shut down every motor immediately'],1,'Maintain aircraft control, understand the degraded mode, and use the preplanned contingency or land safely.',[ref.ac]],
];

const tagFor = (n:number) => n<=12?'regulations':n<=22?'airspace':n<=30?'operations':n<=38?'night-people-remote-id':n<=46?'weather':n<=50?'performance':'adm-emergencies';
export const questions: Question[] = seeds.map(([num,prompt,choices,correctChoiceIndex,explanation,references,difficulty='intermediate']) => ({
  id:`p107-${num}`,trackId:'part-107',objectiveId:tagFor(Number(num)),prompt,
  choices:choices.map((text,index)=>({id:String.fromCharCode(97+index),text})),
  correctChoiceId:String.fromCharCode(97+correctChoiceIndex),explanation,references,difficulty,tags:[tagFor(Number(num))],
}));
