import { useMemo, useState } from 'react';
import type { Question } from '../types/content';
import { scoreQuiz, selectExamQuestions } from '../lib/quiz';

const sizes=[10,25,60,120];
export function Quiz({questions}:{questions:Question[]}){
  const [size,setSize]=useState(10); const [seed,setSeed]=useState(0); const [index,setIndex]=useState(0);
  const [answers,setAnswers]=useState<Record<string,string>>({}); const [submitted,setSubmitted]=useState(false);
  const exam=useMemo(()=>{void seed;return selectExamQuestions(questions,Math.min(size,questions.length));},[questions,size,seed]);
  const current=exam[index]; const result=scoreQuiz(exam,answers);
  const restart=(next=size)=>{setSize(next);setSeed(v=>v+1);setIndex(0);setAnswers({});setSubmitted(false)};
  if(submitted)return <section className="quiz" aria-labelledby="quiz-title"><div className="results"><span className="eyebrow">Practice complete</span><strong>{result.percent}%</strong><h2 id="quiz-title">{result.correct} of {result.total} correct</h2><p>{result.percent>=80?'Strong result. Review the misses, then try a larger set.':'Use the explanations below to target your next study pass.'}</p><button onClick={()=>restart()}>New randomized set</button></div><div className="review-list">{exam.map((q,n)=>{const ok=answers[q.id]===q.correctChoiceId;return <details key={q.id}><summary><span className={ok?'status correct-dot':'status incorrect-dot'}>{ok?'✓':'×'}</span>{n+1}. {q.prompt}</summary><div><b>Your answer:</b> {q.choices.find(c=>c.id===answers[q.id])?.text||'Not answered'}<br/><b>Correct answer:</b> {q.choices.find(c=>c.id===q.correctChoiceId)?.text}<p>{q.explanation}</p><small>{q.references.join(' · ')}</small></div></details>})}</div></section>;
  return <section className="quiz" aria-labelledby="quiz-title"><div className="section-heading"><div><span className="eyebrow">Randomized practice</span><h2 id="quiz-title">Part 107 quiz bank</h2></div><span className="counter">{questions.length} original questions</span></div><div className="quiz-toolbar" aria-label="Quiz length">{sizes.map(n=><button key={n} className={size===n?'chip active':'chip'} onClick={()=>restart(n)}>{n===100?'Full bank':n===60?'60-question simulation':`${n} questions`}</button>)}</div><div className="quiz-progress"><span style={{width:`${((index+1)/exam.length)*100}%`}}></span></div><div className="question-card"><div className="question-meta"><span>Question {index+1} / {exam.length}</span><span>{current.tags[0].replaceAll('-',' ')}</span></div><fieldset><legend>{current.prompt}</legend>{current.choices.map(choice=><label key={choice.id} className={answers[current.id]===choice.id?'selected':''}><input type="radio" name={current.id} value={choice.id} checked={answers[current.id]===choice.id} onChange={()=>setAnswers(a=>({...a,[current.id]:choice.id}))}/><span className="choice-letter">{choice.id.toUpperCase()}</span>{choice.text}</label>)}</fieldset><div className="quiz-nav"><button className="secondary" onClick={()=>setIndex(i=>i-1)} disabled={index===0}>Previous</button>{index<exam.length-1?<button onClick={()=>setIndex(i=>i+1)} disabled={!answers[current.id]}>Next question</button>:<button onClick={()=>setSubmitted(true)} disabled={Object.keys(answers).length!==exam.length}>Grade quiz</button>}</div></div></section>;
}
