import type { Lesson } from '../../../../types/content';
import { sourceRefs as ref } from '../sources';

const lesson = (id:string,title:string,summary:string,objectives:string[],sections:{heading:string;body:string}[],references:string[]): Lesson => ({id,title,summary,objectives,sections,references});

export const studyGuide: Lesson[] = [
  lesson('certificate-and-recurrency','Certification, eligibility & recency','Know who may act as remote PIC and how Part 107 privileges stay current.',
    ['State the eligibility and certification requirements','Distinguish initial testing from recurrent training','Identify required documents and inspection duties'],[
      {heading:'Who needs the certificate',body:'A person acting as remote PIC under Part 107 must hold a remote pilot certificate with a small UAS rating. A person without one may manipulate the controls only while directly supervised by a certificated remote PIC who can immediately take direct control. Applicants must be at least 16, understand English, and be physically and mentally able to operate safely.'},
      {heading:'Initial and recurrent paths',body:'A first-time applicant who does not qualify through the Part 61 pathway passes the UAG knowledge test and completes the FAA application and security-vetting process. To exercise privileges, a remote pilot must complete an accepted knowledge test or online recurrent training within the preceding 24 calendar months. The supplied ALC-677 course is the recurrent route for non-Part 61 pilots and pilots without a current flight review.'},
      {heading:'Documents and conduct',body:'Have the remote pilot certificate and identification available during operations and present them when requested by the FAA, NTSB, TSA, or law-enforcement officers identified by the rule. Drug- and alcohol-related prohibitions, reporting obligations, and refusal-to-test consequences can affect certificate eligibility and privileges.'}], [ref.rules,ref.review,ref.acs]),
  lesson('aircraft-registration','Aircraft, registration & Remote ID','Determine whether the aircraft qualifies, how it is registered, and how it broadcasts identity.',
    ['Define a small UAS and recognize exclusions','Apply registration and marking rules','Compare Remote ID compliance paths'],[
      {heading:'Small UAS boundary and exclusions',body:'A small unmanned aircraft system includes the aircraft and everything required for safe and efficient operation, and must weigh less than 55 pounds at takeoff, including payload. Part 107 does not cover indoor flight, recreational operations conducted solely under their separate statutory exception, or public-aircraft operations conducted under separate authority.'},
      {heading:'Registration and markings',body:'Part 107 operators register each aircraft individually. The registration number must be displayed legibly on an external surface, though it may be inside an accessible compartment that can be opened without tools. Carry proof of registration and keep inventory information current.'},
      {heading:'Remote ID',body:'A required aircraft generally complies through Standard Remote ID, a broadcast module, or operation within the conditions of an FAA-Recognized Identification Area. A broadcast-module aircraft must remain within visual line of sight. Remote ID does not replace registration, airspace authorization, or any operating limitation.'}], [ref.rules,ref.rid,ref.review]),
  lesson('crew-and-responsibility','Remote PIC, crew roles & CRM','Use clear authority, effective communication, and positive transfer of control.',
    ['Explain the authority of the remote PIC','Describe the controller and visual-observer roles','Apply crew resource management'],[
      {heading:'Final authority',body:'The remote PIC is directly responsible for the operation and is the final authority. Before and during flight, the remote PIC verifies safe condition, evaluates the environment, briefs participants, ensures compliance, and has the ability to direct the aircraft or terminate the operation.'},
      {heading:'Supporting roles',body:'A person manipulating the controls flies under the remote PIC’s direct supervision unless separately certificated. A visual observer helps maintain awareness of the aircraft, air traffic, people, obstacles, and changing conditions. One person may not simultaneously serve as remote PIC or visual observer for more than one small UAS operation.'},
      {heading:'Crew coordination',body:'Brief roles, communication terms, scan sectors, lost-link actions, emergency landing areas, and control-transfer language before launch. Use an explicit positive exchange—offer control, acknowledge acceptance, and confirm transfer. Encourage any crewmember to call a hazard and limit nonessential conversation during critical phases.'}], [ref.rules,ref.ac,ref.review]),
  lesson('maintenance-preflight','Maintenance, inspection & preflight','Put the aircraft in a safe condition and evaluate the entire operating environment.',
    ['Distinguish scheduled and unscheduled maintenance','Conduct a complete preflight assessment','Account for software, payload, links, and environmental hazards'],[
      {heading:'Maintenance program',body:'Follow manufacturer inspection, maintenance, overhaul, and life-limit guidance. Record recurring defects and corrective action. After a hard landing, propeller strike, repair, modification, firmware change, or other abnormal event, perform an unscheduled inspection or operational check appropriate to the condition.'},
      {heading:'Aircraft inspection',body:'Before each flight inspect structure, fasteners, landing gear, propellers or rotors, motors, controls, antennas, sensors, wiring, batteries, payload attachment, required lighting, and Remote ID status. Confirm configuration, software compatibility, control response, navigation status, and command-and-control links. Do not launch until every condition affecting safety is corrected.'},
      {heading:'Site and mission assessment',body:'Evaluate weather, airspace, NOTAMs, flight restrictions, terrain, obstacles, electromagnetic interference, people, property, roads, emergency access, launch and recovery areas, and alternate landing sites. Confirm the aircraft, payload, crew, lighting, and authorizations fit the mission.'}], [ref.rules,ref.ac,ref.review]),
  lesson('airspace-and-charts','Airspace, charts, NOTAMs & authorization','Read sectional information and identify when the FAA must authorize the operation.',
    ['Recognize controlled and special-use airspace','Interpret chart symbology and airport data','Use current NOTAM, TFR, and authorization information'],[
      {heading:'Controlled versus uncontrolled',body:'Prior FAA authorization is required in Class B, C, or D airspace and within Class E surface areas designated for an airport. Class G normally requires no Part 107 airspace authorization, but all operating rules still apply. Class A begins at 18,000 feet MSL and is outside normal Part 107 operations.'},
      {heading:'Chart reading',body:'Solid blue, solid magenta, dashed blue, and dashed magenta boundaries identify common controlled-airspace structures. A faded magenta vignette normally indicates a 700-foot AGL Class E floor; faded blue normally indicates 1,200 feet AGL. Read airport elevation, runway alignment, frequencies, obstacles, special-use boundaries, and maximum-elevation figures together.'},
      {heading:'Authorizations and restrictions',body:'LAANC can provide near-real-time approval at or below eligible UAS Facility Map values; the map value itself is not authorization. Check current NOTAMs and TFRs, prohibited and restricted areas, MOAs, warning areas, stadium restrictions, national-security restrictions, and disaster areas. Never interfere with airport traffic or emergency response.'}], [ref.airspace,ref.studyGuide,ref.acs]),
  lesson('operating-limits','VLOS, altitude, speed & right-of-way','Memorize the normal operating envelope and know when a waiver is required.',
    ['Recall altitude, speed, visibility, and cloud-clearance limits','Apply VLOS and right-of-way requirements','Recognize limits on vehicles, carriage, and multiple operations'],[
      {heading:'Core numbers',body:'Maximum groundspeed is 87 knots (100 mph). Maximum altitude is 400 feet AGL, except within 400 feet of a structure where flight may be up to 400 feet above its immediate uppermost limit. Minimum flight visibility is 3 statute miles from the control station; remain 500 feet below and 2,000 feet horizontally from clouds.'},
      {heading:'Visual line of sight',body:'The applicable crewmember must see the aircraft throughout the operation with unaided vision other than corrective lenses well enough to know its location, attitude, altitude, direction, hazards, and risk to people or property. FPV and binoculars may assist momentarily but do not replace VLOS.'},
      {heading:'Priority and prohibited conduct',body:'Yield to every crewed aircraft, airborne vehicle, and launch or reentry vehicle and avoid passing over, under, or ahead unless well clear. Do not operate carelessly or recklessly, from a moving aircraft, or from a moving vehicle except over a sparsely populated area under the rule’s conditions.'}], [ref.limits,ref.rules,ref.acs]),
  lesson('night-and-people','Night flight & operations over people','Apply the added training, lighting, category, and assembly requirements.',
    ['Plan a compliant night operation','Distinguish Categories 1 through 4','Identify restrictions for moving vehicles and open-air assemblies'],[
      {heading:'Night operations',body:'Night operation requires completion of the updated initial test or recurrent training and anti-collision lighting visible for at least 3 statute miles with a flash rate sufficient to avoid collision. The remote PIC may reduce intensity when operating conditions make that safer. Preserve dark adaptation and account for visual illusions and reduced depth perception.'},
      {heading:'Categories over people',body:'Category 1 aircraft weigh 0.55 pound or less throughout the operation and have no exposed rotating parts capable of lacerating skin. Categories 2 and 3 rely on FAA-accepted means and declarations of compliance plus operating restrictions; Category 4 uses an eligible airworthiness certificate and required maintenance and records.'},
      {heading:'Assemblies and moving vehicles',body:'Sustained flight over an open-air assembly has additional Remote ID conditions. Operations over moving vehicles depend on category eligibility and either a closed or restricted-access site with notice to occupants or transit-only conditions; hovering or circling over moving traffic is not mere transit.'}], [ref.night,ref.people,ref.rid]),
  lesson('weather','Weather reports, theory & hazards','Decode aviation weather and translate it into UAS performance and risk.',
    ['Read METAR and TAF elements','Explain stability, fronts, fog, and thunderstorms','Predict wind and density-altitude effects'],[
      {heading:'Reports and forecasts',body:'A METAR is an observation and a TAF is an airport forecast. Decode wind direction and speed, gusts, visibility, weather, ceiling, temperature/dew point, altimeter setting, and forecast change groups. Compare multiple current sources rather than relying on one app display.'},
      {heading:'Air masses and stability',body:'Stable air resists vertical motion and favors smooth air, layered clouds, steady precipitation, and poorer visibility. Unstable air favors turbulence, vertical clouds, showery precipitation, and better visibility away from weather. A shrinking temperature/dew-point spread signals increasing saturation risk.'},
      {heading:'Wind, fronts, and convection',body:'Surface friction changes wind speed and direction, and obstacles create mechanical turbulence and rotor zones. Fronts concentrate changing wind, ceilings, precipitation, and thunderstorms. Thunderstorm outflow, lightning, hail, wind shear, and turbulence can extend well beyond visible rain.'}], [ref.weather,ref.phak,ref.studyGuide]),
  lesson('loading-performance','Loading, batteries & aircraft performance','Predict how mass, balance, environment, and energy reserves change controllability.',
    ['Calculate loading and center-of-gravity effects','Explain density altitude and wind penalties','Build conservative battery reserves'],[
      {heading:'Weight and balance',body:'Include the aircraft, batteries, payload, mounts, guards, and every attached item. Excess weight increases required power and reduces climb and endurance. A center of gravity outside manufacturer limits can reduce stability or exhaust available control authority.'},
      {heading:'Density altitude and wind',body:'High elevation, high temperature, low pressure, and—more modestly—high humidity reduce air density. Propellers and aerodynamic surfaces produce less force for a given setting, increasing power demand. Strong wind, gusts, and turbulence further reduce usable endurance and may prevent a safe return.'},
      {heading:'Battery planning',body:'Use manufacturer limits and observed battery condition, not advertised maximum time. Cold can reduce available capacity; heat and high discharge rates accelerate degradation. Plan the most demanding leg, monitor state of charge under load, establish abort triggers, and preserve a conservative landing reserve.'}], [ref.ac,ref.phak,ref.studyGuide]),
  lesson('airport-radio','Airport operations & radio communication','Interpret runway, traffic-pattern, and radio cues without assuming radio contact is permission.',
    ['Read runway and traffic-pattern indicators','Interpret common aviation calls and frequencies','Avoid conflict with airport traffic'],[
      {heading:'Airport indicators',body:'Runway numbers approximate magnetic direction rounded to the nearest 10 degrees. Wind cones, segmented circles, tetrahedrons, and traffic-pattern indicators show wind or pattern information. Determine likely active runways, pattern altitude and direction, helicopter activity, and approach or departure paths.'},
      {heading:'Radio awareness',body:'Part 107 does not generally require a radio, but monitoring CTAF or tower frequencies can improve awareness. Understand aircraft type, call sign, location, altitude, and intention. Use standard terms such as traffic, final, base, downwind, and clear of runway; do not transmit unless capable and appropriate.'},
      {heading:'No substitute for authorization',body:'A radio call, tower acknowledgment, or airport-manager permission does not replace required FAA airspace authorization. Maintain visual scanning even while monitoring because not every aircraft transmits and reception can be incomplete.'}], [ref.airspace,ref.phak,ref.acs]),
  lesson('adm-and-physiology','ADM, physiology & hazardous attitudes','Recognize human limits and use repeatable decision tools before pressure becomes an accident.',
    ['Apply PAVE and ongoing risk checks','Recognize hazardous attitudes and stress','Apply drug, alcohol, fatigue, and vision limitations'],[
      {heading:'Risk management',body:'Use PAVE—Pilot, Aircraft, enVironment, External pressures—during planning, then repeat an in-flight check such as the 5P model when conditions change. Set objective go/no-go and abort criteria before launch. External pressure, sunk cost, and plan-continuation bias are strongest when limits were not agreed in advance.'},
      {heading:'Hazardous attitudes',body:'Anti-authority, impulsivity, invulnerability, macho behavior, and resignation distort judgment. Counter them with the disciplined response: follow the rules, think first, recognize it can happen, avoid unnecessary risk, and remember that effective action remains possible.'},
      {heading:'Fitness for duty',body:'Do not serve as remote PIC, controller, or visual observer while affected by alcohol, drugs, fatigue, illness, stress, or medication that degrades performance. Eight hours bottle-to-throttle is only a minimum; impairment remains disqualifying. Night vision and depth perception also degrade with fatigue and poor lighting.'}], [ref.phak,ref.rules,ref.acs]),
  lesson('abnormal-emergency-reporting','Abnormal events, emergencies & reporting','Rehearse lost link, flyaway, battery, injury, and notification responses.',
    ['Respond to common abnormal and emergency conditions','Know when an emergency deviation is allowed','Apply FAA and NTSB reporting triggers'],[
      {heading:'Prepared contingencies',body:'Brief lost-link programming, flyaway response, degraded GPS or compass behavior, flight termination, low battery, motor or propeller failure, lithium-battery fire, medical events, people entering the area, and a crewed-aircraft conflict. Protect people first and use the safest preplanned landing or termination option.'},
      {heading:'Emergency authority',body:'In an in-flight emergency requiring immediate action, the remote PIC may deviate from Part 107 only to the extent necessary. Record what happened and provide a written report to the FAA if requested. A waiver is planned relief granted in advance; it is not emergency authority.'},
      {heading:'Accident reporting',body:'Report to the FAA within 10 days when an operation causes serious injury, loss of consciousness, or property damage—other than to the small UAS—of at least $500 to repair or replace. NTSB notification may separately apply to serious incidents or accidents; preserve the facts and consult the current criteria.'}], [ref.rules,ref.review,ref.ac]),
];
