import { tracks } from './content';
import { Quiz } from './components/Quiz';
import { part107Sources } from './content/tracks/part-107/sources';
import './styles.css';
import './sources.css';

export default function App(){
  const current=tracks[0];
  return <><header><a className="brand" href="#top" aria-label="Aero Works home"><span>AW</span>AERO WORKS</a><nav aria-label="Primary"><a href="#guide">Study guide</a><a href="#quiz">Practice</a><a href="#sources">Sources</a><a href="#tracks">Tracks</a></nav></header><main id="top">
    <section className="hero"><div><span className="eyebrow">FAA Part 107 · Study system</span><h1>Know the rules.<br/><em>Think like a pilot.</em></h1><p>{current.description} Work through eight focused briefings, then test yourself against a 60-question bank.</p><div className="hero-actions"><a className="primary" href="#guide">Open study guide</a><a className="text-link" href="#quiz">Take a practice quiz →</a></div></div><div className="radar" aria-hidden="true"><span className="sweep"></span><b>107</b><small>60 QUESTION BANK</small></div></section>
    <section className="stats" aria-label="Study guide overview"><div><strong>08</strong><span>Study briefings</span></div><div><strong>60</strong><span>Practice questions</span></div><div><strong>03</strong><span>Quiz lengths</span></div><div><strong>05</strong><span>Supplied FAA files</span></div></section>
    <section id="guide" className="guide"><div className="section-heading"><div><span className="eyebrow">Part 107 study guide</span><h2>Eight briefings. One flight line.</h2></div><span className="counter">Select a briefing to expand</span></div><p className="lead">Start with the regulations, then move through airspace, weather, aircraft performance, and operational judgment. Every lesson and quiz explanation is traceable to the FAA course files in the linked study folder or to an FAA resource named by those files.</p><div className="guide-list">{current.lessons.map((lesson,index)=><details key={lesson.id} open={index===0}><summary><span className="module-number">{String(index+1).padStart(2,'0')}</span><span><b>{lesson.title}</b><small>{lesson.summary}</small></span><span className="expand">+</span></summary><div className="guide-body"><div className="objectives"><span className="eyebrow">You should be able to</span><ul>{lesson.objectives.map(o=><li key={o}>{o}</li>)}</ul></div><div className="study-sections">{lesson.sections.map(s=><article key={s.heading}><h3>{s.heading}</h3><p>{s.body}</p></article>)}</div><div className="references"><b>Folder provenance</b><span>{lesson.references.join(' · ')}</span></div></div></details>)}</div><aside className="test-note"><strong>Source boundary</strong><p>This edition is intentionally limited to the supplied ALC-677 FAA course files and the resources named inside <i>Resources_UAS-Recurrent-Non61.pdf</i>. Verify the live regulations and FAA notices before an actual operation.</p></aside></section>
    <div id="quiz"><Quiz questions={current.questions}/></div>
    <section id="sources" className="sources"><div className="section-heading"><div><span className="eyebrow">Closed source set</span><h2>What this guide uses</h2></div><span className="counter">Folder files + their links</span></div><div className="source-grid">{part107Sources.map(source=><article key={source.id}><small>{source.kind}</small><h3>{source.url?<a href={source.url} target="_blank" rel="noreferrer">{source.title} ↗</a>:source.title}</h3><p>{source.detail}</p></article>)}</div></section>
    <section id="tracks" className="tracks"><div className="section-heading"><div><span className="eyebrow">Aero Works curriculum</span><h2>Future flight lines</h2></div></div><div className="track-grid">{tracks.map((track,i)=><article key={track.id} className={track.status==='available'?'active':''}><span>0{i+1}</span><h3>{track.shortTitle}</h3><p>{track.description}</p><small>{track.status==='available'?'Available now':'Planned'}</small></article>)}</div></section>
  </main><footer><span>AERO WORKS // BUILD KNOWLEDGE. FLY SMART.</span><span>Educational use only · Verify current FAA guidance</span></footer></>;
}
