import { tracks } from './content';
import { Quiz } from './components/Quiz';
import { part107Sources } from './content/tracks/part-107/sources';
import { quickReference } from './content/tracks/part-107/quick-reference';
import { flashcards } from './content/tracks/part-107/flashcards';
import { Flashcards } from './components/Flashcards';
import './styles.css';
import './sources.css';
import './study-tools.css';

export default function App(){
  const current=tracks[0];
  return <><header><a className="brand" href="#top" aria-label="Aero Works home"><span>AW</span>AERO WORKS</a><nav aria-label="Primary"><a href="#guide">Study guide</a><a href="#quick-reference">Quick reference</a><a href="#flashcards">Flashcards</a><a href="#quiz">Practice</a><a href="#sources">Sources</a></nav></header><main id="top">
    <section className="hero"><div><span className="eyebrow">FAA Part 107 · Study system</span><h1>Know the rules.<br/><em>Think like a pilot.</em></h1><p>{current.description} Work through {current.lessons.length} exam-domain briefings, then test yourself against a {current.questions.length}-question bank.</p><div className="hero-actions"><a className="primary" href="#guide">Open study guide</a><a className="text-link" href="#quiz">Take a practice quiz →</a></div></div><div className="radar" aria-hidden="true"><span className="sweep"></span><b>107</b><small>{current.questions.length} QUESTION BANK</small></div></section>
    <section className="stats" aria-label="Study guide overview"><div><strong>{String(current.lessons.length).padStart(2,'0')}</strong><span>Study briefings</span></div><div><strong>{current.questions.length}</strong><span>Practice questions</span></div><div><strong>{flashcards.length}</strong><span>Flashcards</span></div><div><strong>05</strong><span>Supplied FAA files</span></div></section>
    <section id="guide" className="guide"><div className="section-heading"><div><span className="eyebrow">Part 107 study guide</span><h2>{current.lessons.length} exam domains. One flight line.</h2></div><span className="counter">Select a briefing to expand</span></div><p className="lead">Follow the supplied ALC-677 video from certification and aircraft requirements through crew roles, preflight, operating limitations, abnormal events, and reporting—then reinforce the FAA knowledge-test domains named in the ACS.</p><div className="guide-list">{current.lessons.map((lesson,index)=><details key={lesson.id} open={index===0}><summary><span className="module-number">{String(index+1).padStart(2,'0')}</span><span><b>{lesson.title}</b><small>{lesson.summary}</small></span><span className="expand">+</span></summary><div className="guide-body"><div className="objectives"><span className="eyebrow">You should be able to</span><ul>{lesson.objectives.map(o=><li key={o}>{o}</li>)}</ul></div><div className="study-sections">{lesson.sections.map(s=><article key={s.heading}><h3>{s.heading}</h3><p>{s.body}</p></article>)}</div><div className="references"><b>Folder provenance</b><span>{lesson.references.join(' · ')}</span></div></div></details>)}</div><aside className="test-note"><strong>Exam scope</strong><p>The FAA does not publish the live test questions. This guide follows the official ACS knowledge areas, the supplied ALC-677 training, and FAA references named in <i>Resources_UAS-Recurrent-Non61.pdf</i>. Verify current rules and notices before an actual operation.</p></aside></section>
    <section id="quick-reference" className="quick-reference"><div className="section-heading"><div><span className="eyebrow">Verified memory items</span><h2>Part 107 quick reference</h2></div><span className="counter">Use the rule, not a slogan</span></div><div className="reference-grid">{quickReference.map(group=><article key={group.title}><h3>{group.title}</h3>{group.items.map(item=><div className="reference-item" key={item.label}><small>{item.label}</small><strong>{item.value}</strong><p>{item.note}</p></div>)}<footer>{group.references.join(' · ')}</footer></article>)}</div></section>
    <Flashcards cards={flashcards}/>
    <div id="quiz"><Quiz questions={current.questions}/></div>
    <section id="sources" className="sources"><div className="section-heading"><div><span className="eyebrow">Closed source set</span><h2>What this guide uses</h2></div><span className="counter">Folder files + their links</span></div><div className="source-grid">{part107Sources.map(source=><article key={source.id}><small>{source.kind}</small><h3>{source.url?<a href={source.url} target="_blank" rel="noreferrer">{source.title} ↗</a>:source.title}</h3><p>{source.detail}</p></article>)}</div></section>
    <section id="tracks" className="tracks"><div className="section-heading"><div><span className="eyebrow">Aero Works curriculum</span><h2>Future flight lines</h2></div></div><div className="track-grid">{tracks.map((track,i)=><article key={track.id} className={track.status==='available'?'active':''}><span>0{i+1}</span><h3>{track.shortTitle}</h3><p>{track.description}</p><small>{track.status==='available'?'Available now':'Planned'}</small></article>)}</div></section>
  </main><footer><span>AERO WORKS // BUILD KNOWLEDGE. FLY SMART.</span><span>Educational use only · Verify current FAA guidance</span></footer></>;
}
